### ISSUE TITLE
Can't detect(filter) net::ERR_ errors from GET method response

### ISSUE THREAD

**Issue by iSwanGit** [iSwanGit/John-the-Defender#3]
SSL 인증서 서명문제로 인한 에러(경고)인건지, 개발 불량으로 인한 비보안 항목 경고인건지, 위변조 가능성에 대한 경고인건지, HTTPS 연결 자체가 수립이 안되는건지 구분이 불가능함  
net::ERR_CONNECTION_REFUSED, net::ERR_INSECURE_**RESPONSE** 이라고 브라우저에서는 표현이 되나, ajax에서 error, 0 으로 동일하게 나옴...  
열라게 찾아보니 구분 못한다고...
한계점과 대안책에 대해 생각해볼 것

**Comment by junhyunk** [comment]
크롬 실행 시 flag로 --ignore-certificate-errors 활성화하면 ERR_INSECURE_CONNECTION에 대해서는 bypass 가능하지만, #2 에서 언급한 것처럼 보안 측면에서 좋은 해결책은 아님. Self-Signed Certificate와 같이 인증되지 않은 CA의 인증서에 대해서는 경고 띄우는 게 맞음.

**Comment by iSwanGit** [comment]
경고 띄우는게 맞는데 그걸 extension에서 두 에러를 구분할 수가 없다는 것은 피할 수가 없는건가
extension도 결국은 브라우저 종속이라 브라우저에서 걸리는 건 똑같고

**Comment by iSwanGit** [comment]
## net::에러 틀리게 썼다
### 테스트 중에 보았던 에러들
- ERR_CONNECTION_REFUSED
- ERR_INSECURE_**RESPONSE**
- ERR_CERT_COMMON_NAME_INVALID
- ERR_CERT_AUTHORITY_INVALID
### CERT 에러의 원인  [#출처](https://www.securesign.kr/guides/kb/17)
- 공인 인증기관으로부터 발급 받은 인증서는 "체인인증서" 를 설치하지 않은 경우 (가장 많음)
- 공인 인증서이지만, 스마트폰이 너무 구형이라서 루트인증서를 적절하게 보유하지 못한 경우
- 인증서 발급자로부터 인증서 조회(해외)가 불가한 폐쇄망 환경 
### Chrome ERR references
[#연결 문제 해결](https://support.google.com/chrome/answer/6098869?hl=ko)

**Comment by iSwanGit** [comment]
## ajax xhr에서는 ERR_INSERCURE_RESPONSE 로 퉁쳐짐
## ERR_ABORTED 가 자주 발생하는데 왜일까
